carpooling/carpool/urls.py
from django.urls import path, re_path, include

from . import views

from accounts.views import SignUp

app_name = 'carpool'

urlpatterns = [
    path('create/', views.CreateOfferView.as_view(), name='create-offer'),
    path('alloffers/', views.AllOffersView.as_view(), name='all-offers'),
    path('myoffers/', views.MyOffersView.as_view(), name='my-offers-list'),
    re_path('^myoffers/(?P<pk>\d+)/$', views.MyOffersView.as_view(), name='my-offers'),
    re_path('^offerdetails/(?P<pk>\d+)/$', views.OfferDetailView.as_view(), name='offer-details'),
    re_path('^delete/(?P<pk>\d+)/$', views.OfferDeleteView.as_view(), name='offer-delete'),
    re_path('^edit/(?P<pk>\d+)/$', views.OfferEditView.as_view(), name='offer-edit'),
    path('request/', views.RequestRideView.as_view(), name='request-ride'),
    re_path('^myrequests/(?P<pk>\d+)/$', views.MyRequestsView.as_view(), name='my-requests'),
    path('myrequests/', views.MyRequestsView.as_view(), name='my-requests-list'),
    re_path('^requestdetails/(?P<pk>\d+)/$', views.RequestDetailView.as_view(), name='request-details'),
    re_path('^requestdelete/(?P<pk>\d+)/$', views.RequestDeleteView.as_view(), name='request-delete'),
    path('allrequests/', views.AllRequestsView.as_view(), name='all-requests'),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('signup/', SignUp.as_view(), name='signup'),
]

carpooling/carpooling/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from . import settings

from common import views

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('common/', include('common.urls')),
    path('carpool/', include('carpool.urls')),
    path('', views.get_landing_page, name='home'),
    path('FAQ/', views.AllFAQView.as_view(), name='faq'),
    path('FAQ/additem/', views.AddFAQView.as_view(), name='add-faq'),
    re_path('^FAQ/edititem/(?P<pk>\d+)/$', views.EditFAQView.as_view(), name='edit-faq'),
    re_path('^FAQ/deleteitem/(?P<pk>\d+)/$', views.DeleteFAQView.as_view(), name='delete-faq'),
    path('', include('django.contrib.auth.urls')),

]

if settings.DEBUG:

    # urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carpooling/common/urls.py
from django.urls import path, re_path, include

from . import views


app_name = 'common'

urlpatterns = [
    # path('addfaqitem/', views.AddFAQView.as_view(), name='add-faq'),
]

carpooling/carpool/forms.py
from django import forms

from .models import Offer, SeatRequest


class CreateOfferForm(forms.ModelForm):
    select_regularity = Offer.REGULARITY
    select_districts = Offer.DISTRICTS
    select_seats = Offer.NUMBER_OF_SEATS
    select_contact = Offer.TYPE_OF_CONTACT

    start_location = forms.ChoiceField(choices=select_districts,
                                       widget=forms.Select(
                                           attrs={
                                               'class': 'form-control'
                                           }
                                       ))
    destination = forms.CharField(max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    departure_time = forms.TimeField(required=True, widget=forms.TimeInput(
        attrs={
            'class': 'form-control'
        }
    ))
    return_time = forms.TimeField(required=True, widget=forms.TimeInput(attrs={
        'class': 'form-control'
    }
    ))
    route = forms.CharField(max_length=400, widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    regularity = forms.MultipleChoiceField(choices=select_regularity, widget=forms.SelectMultiple(
        attrs={
            'class': 'form-control'
        }
    ))
    type_of_contact = forms.ChoiceField(choices=select_contact,
                                        widget=forms.Select(
                                            attrs={
                                                'class': 'form-control'
                                            }
                                        ))
    car_picture = forms.ImageField(required=False, label='Upload image')
    number_of_seats = forms.ChoiceField(choices=select_seats,
                                        widget=forms.Select(
                                            attrs={
                                                'class': 'form-control'
                                            }
                                        ))
    passenger = forms.CharField(max_length=70, widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))

    terms_and_conditions = forms.BooleanField()

    class Meta:
        model = Offer
        fields = ['start_location', 'destination', 'departure_time', 'return_time', 'route', 'regularity',
                  'type_of_contact', 'number_of_seats', 'passenger', 'car_picture', 'terms_and_conditions']

    def __init__(self, *args, **kwargs):
        super(CreateOfferForm, self).__init__(*args, **kwargs)
        self.fields['regularity'].widget = forms.CheckboxSelectMultiple(choices=Offer.REGULARITY)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.owner = self.request.user
        obj.save()
        return super().form_valid(form)


class EditOfferForm(forms.ModelForm):
    select_regularity = Offer.REGULARITY
    select_districts = Offer.DISTRICTS
    select_seats = Offer.NUMBER_OF_SEATS
    select_contact = Offer.TYPE_OF_CONTACT

    start_location = forms.ChoiceField(choices=select_districts,
                                       widget=forms.Select(
                                           attrs={
                                               'class': 'form-control'
                                           }
                                       ))
    destination = forms.CharField(max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    departure_time = forms.TimeField(required=True, widget=forms.TimeInput(
        attrs={
            'class': 'form-control'
        }
    ))
    return_time = forms.TimeField(required=True, widget=forms.TimeInput(attrs={
        'class': 'form-control'
    }
    ))
    route = forms.CharField(max_length=400, widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    regularity = forms.MultipleChoiceField(choices=select_regularity, widget=forms.SelectMultiple(
        attrs={
            'class': 'form-control'
        }
    ))
    number_of_seats = forms.ChoiceField(choices=select_seats,
                                        widget=forms.Select(
                                            attrs={
                                                'class': 'form-control'
                                            }
                                        ))
    passenger = forms.CharField(max_length=70, widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    car_picture = forms.ImageField(required=False, label='Upload image')

    class Meta:
        model = Offer
        fields = ['start_location', 'destination', 'departure_time', 'return_time', 'route', 'regularity',
                  'number_of_seats', 'passenger', 'car_picture', 'terms_and_conditions']

    def __init__(self, *args, **kwargs):
        super(EditOfferForm, self).__init__(*args, **kwargs)
        self.fields['regularity'].widget = forms.CheckboxSelectMultiple(choices=Offer.REGULARITY)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.owner = self.request.user
        obj.save()
        return super().form_valid(form)


class RequestRideForm(forms.ModelForm):
    ride_id = forms.ModelChoiceField(queryset=Offer.objects.all(),
                                     widget=forms.Select(attrs={
                                         'class': 'form-control'
                                     }))

    comments = forms.CharField(max_length=400, required=False, widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    ))
    terms_and_conditions = forms.BooleanField()

    class Meta:
        model = SeatRequest
        fields = ['ride_id', 'comments', 'terms_and_conditions']
        exclude = ['passenger']

carpooling/carpool/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from accounts.models import ProfileUser
from .forms import CreateOfferForm, RequestRideForm
from .models import Offer, SeatRequest


# Create your views here.

def has_access_to_modify(current_user, current_obj):
    profile_user = ProfileUser.objects.all().filter(user__pk=current_user.id).first()

    if current_obj.user == profile_user or current_user.is_superuser:
        return True
    return False


def get_all_offers(request):
    # driver = request.GET.get('username')
    offers = Offer.objects.all()
    url = reverse_lazy('carpool:all-offers')
    return HttpResponse(url)



class CreateOfferView(LoginRequiredMixin, generic.CreateView):
    model = Offer
    form_class = CreateOfferForm
    success_url = reverse_lazy('carpool:my-offers-list')
    template_name = 'create_offer.html'

    def form_valid(self, form):
        user = ProfileUser.objects.all().filter(user__pk=self.request.user.id).first()
        form.instance.user = user
        return super().form_valid(form)

    def upload_picture(self, request):
        if request.method == 'POST':
            form = CreateOfferForm(request.POST, request.FILES)
            if form.is_valid():
                offer = Offer()
                offer.car_picture = form.cleaned_data['car_picture']
                offer.save()
        return render(request, 'create_offer.html')

    def post(self, request, *args, **kwargs):
        # if request.method == 'POST':
        form = CreateOfferForm(request.POST, request.FILES)
        if form.is_valid():
            offer = form.save(commit=False)
            # offer.driver = ProfileUser.objects.get(user=self.request.user)  # use your own profile here
            offer.user = ProfileUser.objects.get(user=request.user)
            offer.car_picture = form.cleaned_data['car_picture']
            offer.save()
            return HttpResponseRedirect(reverse_lazy('carpool:my-offers-list'))
        return render(request, 'create_offer.html', {'form': form})


class MyOffersView(LoginRequiredMixin, generic.ListView):
    model = Offer
    template_name = 'my_offers.html'
    context_object_name = 'offers'
    offers_count = Offer.objects.count()

    def get_queryset(self):
        profile_user = ProfileUser.objects.all().filter(user__pk=self.request.user.id).first()
        offers = Offer.objects.all().filter(user=profile_user)
        if offers:
            return offers
        return []


class OfferDetailView(LoginRequiredMixin, generic.DetailView):
    model = Offer
    login_url = 'accounts/login/'
    context_object_name = 'offers'
    template_name = 'offer_details.html'

    def get_context_data(self, object_list=None, **kwargs):
        context = super(OfferDetailView, self).get_context_data(**kwargs)

        if has_access_to_modify(self.request.user, self.get_object()):
            context['is_user_offer'] = True
        else:
            context['is_user_offer'] = False

        return context


class AllOffersView(LoginRequiredMixin, generic.ListView):
    model = Offer
    template_name = 'all_offers.html'
    context_object_name = 'offers'

    def get_queryset(self):
        offers = Offer.objects.all()
        if offers:
            return offers
        return []


class OfferDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Offer
    login_url = 'accounts/login/'
    template_name = 'offer_delete.html'
    success_url = reverse_lazy('carpool:my-offers-list')

    def get(self, request, pk):
        if has_access_to_modify(self.request.user, self.get_object()):
            return render(request, 'offer_delete.html', {'offers': self.get_object()})
        return render(request, 'permission_denied.html')

    def post(self, request, pk):
        if not has_access_to_modify(self.request.user, self.get_object()):
            return render(request, 'permission_denied.html')
        try:
            offer = Offer.objects.get(pk=pk)
            offer.delete()
        except Exception as error:
            print(f"cant delete --> {error}")
        return HttpResponseRedirect(reverse_lazy('carpool:my-offers-list'))



class OfferEditView(LoginRequiredMixin, generic.UpdateView):
    model = Offer
    form_class = CreateOfferForm
    template_name = 'edit_offer.html'
    success_url = reverse_lazy('carpool:my-offers-list')
    context_object_name = 'offers'

    def dispatch(self, request, *args, **kwargs):
        handler = super(OfferEditView, self).dispatch(request, *args, **kwargs)
        # Only allow editing if current user is owner
        if str(self.object.user) == str(request.user) or request.user.is_superuser:
            return handler
        return render(request, 'permission_denied.html')



class RequestRideView(LoginRequiredMixin, generic.CreateView):
    model = SeatRequest
    form_class = RequestRideForm
    template_name = 'request_ride.html'
    success_url = reverse_lazy('carpool:my-requests-list')


    def post(self, request, *args, **kwargs):
        form = RequestRideForm(request.POST)
        if form.is_valid():
            ride_request = form.save(commit=False)
            ride_request.user = ProfileUser.objects.get(user=request.user)
            ride_request.save()
            return HttpResponseRedirect(reverse_lazy('carpool:my-requests-list'))
        return render(request, 'request_ride.html', {'form': form})






class MyRequestsView(LoginRequiredMixin, generic.ListView):
    model = SeatRequest
    template_name = 'my_requests.html'
    context_object_name = 'request'

    def get_queryset(self):
        profile_user = ProfileUser.objects.all().filter(user__pk=self.request.user.id).first()
        offers = SeatRequest.objects.all().filter(user=profile_user)
        if offers:
            return offers
        return []


class AllRequestsView(LoginRequiredMixin, generic.ListView):
    model = SeatRequest
    template_name = 'all_requests.html'
    context_object_name = 'requests'

    def get_queryset(self):
        requests = SeatRequest.objects.all()
        if requests:
            return requests
        return []



class RequestDetailView(LoginRequiredMixin, generic.DetailView):
    model = SeatRequest
    login_url = 'accounts/login/'
    context_object_name = 'requests'
    template_name = 'request_details.html'

    def get_context_data(self, object_list=None, **kwargs):
        context = super(RequestDetailView, self).get_context_data(**kwargs)
        # context['reviews'] = Review.objects.all().filter(offer=self.get_object())

        if has_access_to_modify(self.request.user, self.get_object()):
            context['is_user_offer'] = True
        else:
            context['is_user_offer'] = False

        return context



class RequestDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = SeatRequest
    login_url = 'accounts/login/'
    template_name = 'request_delete.html'
    success_url = reverse_lazy('carpool:my-requests-list')

    def get(self, request, pk):
        if has_access_to_modify(self.request.user, self.get_object()):
            return render(request, 'request_delete.html', {'requests': self.get_object()})
        return render(request, 'permission_denied.html')

    def post(self, request, pk):
        if not has_access_to_modify(self.request.user, self.get_object()):
            return render(request, 'permission_denied.html')
        ride_request = self.get_object()
        ride_request.delete()
        return HttpResponseRedirect(reverse_lazy('carpool:my-requests-list'))

carpooling/carpool/templates/all_offers.html
{% extends 'index.html' %}

{% block 'body' %}

{% load static %}


<div class="container" style="margin-top: 5%;">
    <div class="row">
        {% for offer in offers %}
        <div class="col-lg-4">
            <div class="card" style="width: 18rem;">
                <img src="{{offer.car_picture.url}}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{offer.user}}</h5>
                    <p class="card-text">{{offer.start_location}}</p>
                    <a href="{% url 'carpool:offer-details' offer.id %}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

carpooling/carpool/templates/all_requests.html
{% extends 'index.html' %}

{% block 'body' %}

{% load static %}


<div class="container" style="margin-top: 5%;">
    <div class="row">
        {% for request in requests %}
        <div class="col-lg-4">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{request.user}}</h5>
                    <h5 class="card-title">{{request.driver}}</h5>
                    <h5 class="card-title">{{request.ride_id}}</h5>

                    <a href="{% url 'carpool:request-details' request.id %}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

carpooling/carpool/templates/create_offer.html
{% extends 'index.html' %}

{% block 'body' %}

{% load static %}

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">

        <form style="border: 1px solid grey; margin: 10% 0%; padding: 10% 5%" method="post" enctype="multipart/form-data" action="{% url 'carpool:create-offer' %}" >
            <h2>Create Offer</h2>
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Submit</button>

        </form>
    </div>
    <div class="col-lg-3"></div>
</div>


{% endblock %}

carpooling/carpool/templates/edit_offer.html
{% extends 'index.html' %}

{% block 'body' %}

    {% load static %}

    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">

            <form style="border: 1px solid grey; margin: 10% 0%; padding: 10% 5%" method="post"
                  enctype="multipart/form-data" action="{% url 'carpool:offer-edit' offers.id %}">
                <h2>Edit Offer</h2>
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-primary" type="submit">Update</button>

            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>


{% endblock %}

carpooling/carpool/templates/my_offers.html
{% extends 'index.html' %}

{% block 'body' %}

    {% load static %}

    <div class="container" style="margin-top: 5%;">
        <div class="row">

            {% if not offers %}
                <h1>No offers yet. <a href="{% url 'carpool:create-offer' %}">Create one?</a></h1>
            {% endif %}

            {% for offer in offers %}
                <div class="col-lg-4">
                    <div class="card" style="width: 18rem;">
                        <img src="{{ offer.car_picture.url }}" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">{{ offer.driver }}</h5>
                            <p class="card-text">{{ offer.number_of_seats }}</p>
                            <p class="card-text">{{ offer.start_location }}</p>

                            <a href="{% url 'carpool:offer-details' offer.id %}" class="btn btn-primary">Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

carpooling/carpool/templates/my_requests.html
{% extends 'index.html' %}

{% block 'body' %}

{% load static %}

<div class="container" style="margin-top: 5%;">
    <div class="row">
        {% for r in request %}
        <div class="col-lg-4">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{r.driver}}</h5>
                    <h5 class="card-title">{{r.ride_id}}</h5>

                    <a href="{% url 'carpool:request-details' r.pk %}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

carpooling/carpool/templates/offer_delete.html
{% extends 'index.html' %}

{% block 'body' %}

    {% load static %}

    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>Are you sure you want to delete {{ offers.id }}?</h1>
            <div class="row">
                <div class="col-lg-6">
                    <form method="post">
                        {% csrf_token %}
                        <input type="submit" value="Confirm" class="btn btn-danger"/>
                    </form>
                </div>
                <div class="col-lg-6">
                    <a href="{% url 'carpool:offer-details' offers.id %}" class="btn btn-primary">No, go back</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

carpooling/carpool/templates/offer_details.html
{% extends 'index.html' %}

{% block 'body' %}

    {% load static %}


    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <img src="{{ offers.car_picture.url }}" style="width:100%" alt="">
            </div>
            <div class="col-lg-6">
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 20%">
                        <h3>Name: {{ offers.user }}</h3>
                        <h3>Number of seats: {{ offers.number_of_seats }}</h3>
                        <h3>Start Location: {{ offers.start_location }}</h3>
                        <p>Departure Time: {{ offers.departure_time }}</p>
                        <p>Departure Time: {{ offers.return_time }}</p>
                        <p>Regularity: {{ offers.regularity }}</p>

                        {% if is_user_offer %}
                            <a href="{% url 'carpool:offer-edit' offers.id %}" class="btn btn-success">Edit</a>
                            <a href="{% url 'carpool:offer-delete' offers.id %}" class="btn btn-danger">Delete</a>
                            {% else %}
                            <a href="{% url 'carpool:request-ride' %}" class="btn btn-success">Request</a>

                        {% endif %}


                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

carpooling/carpool/templates/request_delete.html
{% extends 'index.html' %}

{% block 'body' %}

{% load static %}

<div class="row">
        <div class="col-lg-12 text-center">
            <h1>Are you sure you want to delete {{requests.id}}?</h1>
            <div class="row">
                     <div class="col-lg-6">
                         <form method="post">
                            {% csrf_token %}
                                <input type="submit" value="Confirm" class="btn btn-danger" />
                         </form>
                    </div>
                    <div class="col-lg-6">
                        <a  href="{% url 'carpool:request-details' requests.id %}" class="btn btn-primary">No, go back</a>
                    </div>
            </div>
        </div>
    </div>

{% endblock %}

carpooling/carpool/templates/request_details.html
{% extends 'index.html' %}

{% block 'body' %}

    {% load static %}


    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <img src="{{ requests.car_picture.url }}" style="width:100%" alt="">
            </div>
            <div class="col-lg-6">
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 20%">
                        <h3>Name: {{ requests.user }}</h3>
                        <h3>Info: {{ requests.ride_id }}</h3>
                        <h3>Comments: {{ requests.comments }}</h3>

                        {% if is_user_offer %}
                            <a href="{% url 'carpool:request-delete' requests.id %}" class="btn btn-danger">Delete</a>
                        {% endif %}


                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

carpooling/carpool/templates/request_ride.html
{% extends 'index.html' %}

{% block 'body' %}

{% load static %}

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">

        <form style="border: 1px solid grey; margin: 10% 0%; padding: 10% 5%" method="post" enctype="multipart/form-data" action="{% url 'carpool:request-ride' %}" >
            <h2>Create Offer</h2>
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Submit</button>

        </form>
    </div>
    <div class="col-lg-3"></div>
</div>


{% endblock %}