carpooling/accounts/urls.py
from django.urls import path, re_path, include

from . import views

app_name = 'accounts'

urlpatterns = [
    # re_path(r'^profile/(?P<pk>\d+)/$', views.UserDetail.as_view(), name='user-profile'),
    path('profile/<username>/', views.UserDetail.as_view(), name='user-profile'),

    # re_path('profile/(?P<pk>\d+)/', views.UserDetail.as_view(), name='user-profile'),
    path('profile/', views.redirect_user, name='profile'),
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('', include('carpool.urls', namespace='carpool'))

]

carpooling/carpool/urls.py
from django.urls import path, re_path, include

from . import views

from accounts.views import SignUp

app_name = 'carpool'

urlpatterns = [
    path('create/', views.CreateOfferView.as_view(), name='create-offer'),
    path('alloffers/', views.AllOffersView.as_view(), name='all-offers'),
    path('myoffers/', views.MyOffersView.as_view(), name='my-offers-list'),
    re_path('^myoffers/(?P<pk>\d+)/$', views.MyOffersView.as_view(), name='my-offers'),
    re_path('^offerdetails/(?P<pk>\d+)/$', views.OfferDetailView.as_view(), name='offer-details'),
    re_path('^delete/(?P<pk>\d+)/$', views.OfferDeleteView.as_view(), name='offer-delete'),
    re_path('^edit/(?P<pk>\d+)/$', views.OfferEditView.as_view(), name='offer-edit'),
    path('request/', views.RequestRideView.as_view(), name='request-ride'),
    re_path('^myrequests/(?P<pk>\d+)/$', views.MyRequestsView.as_view(), name='my-requests'),
    path('myrequests/', views.MyRequestsView.as_view(), name='my-requests-list'),
    re_path('^requestdetails/(?P<pk>\d+)/$', views.RequestDetailView.as_view(), name='request-details'),
    re_path('^requestdelete/(?P<pk>\d+)/$', views.RequestDeleteView.as_view(), name='request-delete'),
    path('allrequests/', views.AllRequestsView.as_view(), name='all-requests'),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('signup/', SignUp.as_view(), name='signup'),
]

carpooling/carpooling/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from . import settings

from common import views

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('common/', include('common.urls')),
    path('carpool/', include('carpool.urls')),
    path('', views.get_landing_page, name='home'),
    path('FAQ/', views.AllFAQView.as_view(), name='faq'),
    path('FAQ/additem/', views.AddFAQView.as_view(), name='add-faq'),
    re_path('^FAQ/edititem/(?P<pk>\d+)/$', views.EditFAQView.as_view(), name='edit-faq'),
    re_path('^FAQ/deleteitem/(?P<pk>\d+)/$', views.DeleteFAQView.as_view(), name='delete-faq'),
    path('', include('django.contrib.auth.urls')),

]

if settings.DEBUG:

    # urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carpooling/common/urls.py
from django.urls import path, re_path, include

from . import views


app_name = 'common'

urlpatterns = [
    # path('addfaqitem/', views.AddFAQView.as_view(), name='add-faq'),
]

carpooling/common/models.py
from django.db import models


# Create your models here.
class FAQ(models.Model):
    question = models.CharField(max_length=255, blank=False, null=False, default='question')
    answer = models.TextField(max_length=1400, blank=False, default='answer')

    def __str__(self):
        return f"{self.id} - {self.question}"

carpooling/common/forms.py
from django import forms

from .models import FAQ


class AddFAQForm(forms.ModelForm):
    question = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={
                                         'class': 'form-control'
                                     }))

    answer = forms.CharField(max_length=1400, required=True, widget=forms.Textarea(
        attrs={
            'class': 'form-control'
        }
    ))

    class Meta:
        model = FAQ
        fields = ['question', 'answer']

    def __init__(self, *args, **kwargs):
        super(AddFAQForm, self).__init__(*args, **kwargs)


    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.owner = self.request.user
        obj.save()
        return super().form_valid(form)

carpooling/common/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views import generic


from .models import FAQ
from .forms import AddFAQForm

# Create your views here.

def has_access_to_add_or_modify(current_user):

    if current_user.is_superuser:
        return True
    return False


def get_landing_page(request):
    # ('common/templates/landing-page.html')
    return render(request, 'landing-page.html')

#
# def get_faq_page(request):
#     # ('common/templates/landing-page.html')
#     return render(request, 'FAQ.html')


class AddFAQView(LoginRequiredMixin, generic.CreateView):
    model = FAQ
    form_class = AddFAQForm
    success_url = reverse_lazy('faq')
    template_name = 'add_faq_item.html'
    context_object_name = 'faq'


    def post(self, request, *args, **kwargs):
        form = AddFAQForm(request.POST)
        if not has_access_to_add_or_modify(self.request.user):
            return render(request, 'permission_denied.html')
        faq = form.save(commit=False)
        faq.question = form.cleaned_data['question']
        faq.answer = form.cleaned_data['answer']
        faq.save()
        return HttpResponseRedirect(reverse_lazy('faq'))


class AllFAQView(generic.ListView):
    model = FAQ
    template_name = 'FAQ.html'
    context_object_name = 'faqs'

    def get_queryset(self):
        offers = FAQ.objects.all()
        if offers:
            return offers
        return []



class EditFAQView(LoginRequiredMixin, generic.UpdateView):
    model = FAQ
    form_class = AddFAQForm
    template_name = 'edit_faq_item.html'
    success_url = reverse_lazy('faq')
    context_object_name = 'faqs'

    def dispatch(self, request, *args, **kwargs):
        handler = super(EditFAQView, self).dispatch(request, *args, **kwargs)
        # Only allow editing if current user is owner
        if request.user.is_superuser:
            return handler
        return render(request, 'permission_denied.html')



class DeleteFAQView(LoginRequiredMixin, generic.DeleteView):
    model = FAQ
    login_url = 'accounts/login/'
    template_name = 'delete_faq_item.html'
    success_url = reverse_lazy('faq')

    def get(self, request, pk):
        if has_access_to_add_or_modify(self.request.user):
            return render(request, 'delete_faq_item.html', {'faqs': self.get_object()})
        return render(request, 'permission_denied.html')

    def post(self, request, pk):
        if not has_access_to_add_or_modify(self.request.user):
            return render(request, 'permission_denied.html')
        try:
            faq = FAQ.objects.get(pk=pk)
            faq.delete()
        except Exception as error:
            print(f"cant delete --> {error}")
        return HttpResponseRedirect(reverse_lazy('faq'))

carpooling/common/templates/FAQ.html
{% extends 'index.html' %}

{% block 'body' %}

    {% load static %}

    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <h2>Frequently Asked Questions </h2>
            </div>
        </div>
        <p></p>
    <div class="panel-group" id="accordion">
        {% for faq in faqs %}

            <div class="container">
            <div class="row">
            <div class="col-lg-8">
                <div class="tab-content" id="faq-tab-content">
                    <div class="tab-pane show active" id="tab1" role="tabpanel" aria-labelledby="tab1">
                        <div class="accordion" id="accordion-tab-1">
                            <div class="card">
                                <div class="card-header" id="accordion-tab-1-heading-1">
                                    <h5>
                                        <button class="btn btn-link" type="button"  data-target="#accordion-tab-1-content-1" aria-expanded="false" aria-controls="accordion-tab-1-content-1">{{ faq.question }}</button>
                                    </h5>
                                    {% if user.is_superuser %}
                                        <a href="{% url 'edit-faq' faq.id %}" class="btn btn-success faq">Edit</a>
                                        <a href="{% url 'delete-faq' faq.id %}" class="btn btn-danger faq">Delete</a>
                                    {% endif %}
                                </div>
                                <div class="collapse show" id="accordion-tab-1-content-1" aria-labelledby="accordion-tab-1-heading-1" data-parent="#accordion-tab-1">
                                    <div class="card-body">
                                        <p>{{ faq.answer }}</p>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>

{% endblock %}

carpooling/common/templates/add_faq_item.html
{% extends 'index.html' %}

{% block 'body' %}

    {% load static %}



    {% if user.is_superuser %}
        <div class="container" style="margin-top: 5%;>
        <div class="row">
            <div class="col-lg-3"></div>
            <form style="border: 1px solid grey; margin: 10% 0%; padding: 10% 5%" method="post"
                  action="{% url 'add-faq' %}">
                <h2>Add FAQ</h2>
                {% csrf_token %}
                {{ form.as_p }}

                <button class="btn btn-primary" type="submit">Post</button>

            </form>
        </div>
        <div class="col-lg-3"></div>
        </div>
        </div>
    {% else %}
        <h1 class="alert alert-danger">You have no permissions!</h1>
    {% endif %}

{% endblock %}

carpooling/common/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

carpooling/common/templates/delete_faq_item.html
{% extends 'index.html' %}

{% block 'body' %}

    {% load static %}



    {% if user.is_superuser %}
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>Are you sure you want to delete {{ faqs.id }}?</h1>
            <div class="row">
                <div class="col-lg-6">
                    <form method="post">
                        {% csrf_token %}
                        <input type="submit" value="Confirm" class="btn btn-danger"/>
                    </form>
                </div>
                <div class="col-lg-6">
                    <a href="{% url 'delete-faq' faqs.id %}" class="btn btn-primary">No, go back</a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

{% endblock %}

carpooling/common/templates/edit_faq_item.html
{% extends 'index.html' %}

{% block 'body' %}

    {% load static %}



    {% if user.is_superuser %}
        <div class="container" style="margin-top: 5%;>
        <div class=" row">
        <div class="col-lg-3"></div>
        <form style="border: 1px solid grey; margin: 10% 0%; padding: 10% 5%" method="post" action="{% url 'edit-faq' faqs.id %}">
            <h2>Edit FAQ</h2>
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Update</button>
        </form>
        </div>
        <div class="col-lg-3"></div>
    {% endif %}

{% endblock %}

carpooling/common/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Carpooling</title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v5.8.2/js/all.js" integrity="sha384-DJ25uNYET2XCl5ZF++U8eNxPWqcKohUUBUpKGlNLMchM7q4Wjg2CUpjHLaL8yYPH" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>

{% include 'navbar.html' %}

{% block 'body' %}

{% endblock %}

</body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>


</html>

carpooling/common/templates/landing-page.html
{% extends 'index.html' %}

{% load static %}


{% block 'body' %}
    <div class="card-header" style="text-align: center">
        <img class="header" src="{% static 'media/knowstartup-carpooling1.png' %}" alt="home-pic">
    </div>

    <div class="card-body" style="text-align: center">

        <button class="btn btn-primary"><i class="fas fa-user-friends fa-2x"></i> <a
                href="{% url 'carpool:all-offers' %}"> Find a ride</a>

        </button>
        <button class="btn btn-primary"><i class="fas fa-car fa-2x"></i> <a href="{% url 'carpool:create-offer' %}">
            Offer a ride</a>

        </button>

    </div>

    {% if not request.user.is_authenticated %}

        <div class="card-body" style="text-align: center">

            <button class="btn btn-primary"><i class="fas fa-user-plus fa-2x"></i> <a
                    href="{% url 'accounts:signup' %}"> Create an account</a>
            </button>

        </div>

    {% endif %}
{% endblock %}

carpooling/common/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'media/carpool-logo.png' %}" alt="logo"
                                                         style="height: 70px; width: 70px;"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'carpool:all-offers' %}">Offers <span class="sr-only">(current)</span></a>
            </li>


            {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
            {% else %}


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url 'home' %}" id="" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">Menu</a>

                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'carpool:all-offers' %}">All offers</a>
                        <a class="dropdown-item" href="{% url 'carpool:create-offer' %}">Create offer</a>
                        <a class="dropdown-item" href="{% url 'carpool:my-offers-list' %}">My offers</a>
                        <a class="dropdown-item" href="{% url 'carpool:my-requests-list' %}">My requests</a>
                        {% if user.is_superuser %}
                            <a class="dropdown-item" href="{% url 'carpool:all-requests' %}">All requests</a>
                        {% endif %}

                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% if user.is_superuser %}
                            <a class="dropdown-item" href="{% url 'carpool:create-offer' %}">Add offer</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'accounts:user-profile' user.username %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}?next=/accounts/login/">Logout</a>
                    </div>
                </li>

            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'faq' %}">FAQ </a>
            </li>
            {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add-faq' %}">Add FAQ item </a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

carpooling/common/templates/permission_denied.html
{% extends 'index.html' %}

{% block 'body' %}

    {% load static %}

<div class="row">
    <div class="col-lg-12 text-center">
        <div class="alert alert-danger">
            <h1>You do not have permission!</h1>
        </div>
    </div>
</div>

{% endblock %}